import hashlib
import os


PACKAGE_ENCODER_SHA256 = (
    "3243e12f542273733171d972b92e5a2389f43d58afcce636590cbaf32fae834d"
)


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as input_file:
        for chunk in iter(lambda: input_file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def verify_package_encoder(path):
    actual = sha256_file(path)
    if actual != PACKAGE_ENCODER_SHA256:
        raise RuntimeError(
            "The selected encoder is not the HM16.3-standard.exe from the supplied "
            f"archive. Expected SHA256={PACKAGE_ENCODER_SHA256}, actual={actual}."
        )
    return actual


def write_ldp_config(
    path,
    input_file,
    bitstream_file,
    recon_file,
    frame_rate,
    width,
    height,
    frame_count,
    qp,
):
    if width <= 0 or height <= 0 or width % 2 or height % 2:
        raise ValueError("HM YUV420 dimensions must be positive even numbers.")
    if frame_rate <= 0 or frame_count <= 0:
        raise ValueError("Frame rate and frame count must be positive.")
    if not 0 <= qp <= 51:
        raise ValueError("HM 16.3 supports QP values in [0, 51].")

    # These coding parameters are a direct transcription of 1.cfg generated by
    # cfg_hm16.3_LDP.exe in the supplied package. Only I/O fields and QP vary.
    config = f"""#======== File I/O =====================
InputFile                     : {input_file}
InputBitDepth                 : 8
FrameRate                     : {frame_rate}
FrameSkip                     : 0
SourceWidth                   : {width}
SourceHeight                  : {height}
FramesToBeEncoded             : {frame_count}
BitstreamFile                 : {bitstream_file}
ReconFile                     : {recon_file}

#======== Profile ================
Profile                       : main

#======== Unit definition ================
MaxCUWidth                    : 64
MaxCUHeight                   : 64
MaxPartitionDepth             : 4
QuadtreeTULog2MaxSize         : 5
QuadtreeTULog2MinSize         : 2
QuadtreeTUMaxDepthInter       : 3
QuadtreeTUMaxDepthIntra       : 3

#======== Coding Structure =============
IntraPeriod                   : -1
DecodingRefreshType           : 0
GOPSize                       : 4
Frame1:  P    1   3        0.4624   0            0               0           4                4         -1 -5 -9 -13       0
Frame2:  P    2   2        0.4624   0            0               0           4                4         -1 -2 -6 -10       1      -1       5         1 1 1 0 1
Frame3:  P    3   3        0.4624   0            0               0           4                4         -1 -3 -7 -11       1      -1       5         0 1 1 1 1
Frame4:  P    4   1        0.578    0            0               0           4                4         -1 -4 -8 -12       1      -1       5         0 1 1 1 1

#=========== Motion Search =============
FastSearch                    : 1
SearchRange                   : 64
BipredSearchRange             : 4
HadamardME                    : 1
FEN                           : 1
FDM                           : 1

#======== Quantization =============
QP                            : {qp}
MaxDeltaQP                    : 0
MaxCuDQPDepth                 : 0
DeltaQpRD                     : 0
RDOQ                          : 1
RDOQTS                        : 1

#=========== Deblock Filter ============
DeblockingFilterControlPresent: 0
LoopFilterOffsetInPPS         : 0
LoopFilterDisable             : 0
LoopFilterBetaOffset_div2     : 0
LoopFilterTcOffset_div2       : 0
DeblockingFilterMetric        : 0

#=========== Misc. ============
InternalBitDepth              : 8

#=========== Coding Tools =================
SAO                           : 1
AMP                           : 1
TransformSkip                 : 1
TransformSkipFast             : 1
SAOLcuBoundary                : 0

#============ Slices ================
SliceMode                     : 0
SliceArgument                 : 1500
LFCrossSliceBoundaryFlag      : 1

#============ PCM ================
PCMEnabledFlag                : 0
PCMLog2MaxSize                : 5
PCMLog2MinSize                : 3
PCMInputBitDepthFlag          : 1
PCMFilterDisableFlag          : 0

#============ Tiles ================
UniformSpacingIdc             : 0
NumTileColumnsMinus1          : 0
ColumnWidthArray              : 2 3
NumTileRowsMinus1             : 0
RowHeightArray                : 2
LFCrossTileBoundaryFlag       : 1

#============ WaveFront ================
WaveFrontSynchro              : 0

#=========== Quantization Matrix =================
ScalingList                   : 0
ScalingListFile               : scaling_list.txt

#============ Lossless ================
TransquantBypassEnableFlag    : 0
CUTransquantBypassFlagForce   : 0

#============ Rate Control ======================
RateControl                   : 0
TargetBitrate                 : 100000
KeepHierarchicalBit           : 2
LCULevelRateControl           : 1
RCLCUSeparateModel            : 1
InitialQP                     : 0
RCForceIntraQP                : 0

### DO NOT ADD ANYTHING BELOW THIS LINE ###
### DO NOT DELETE THE EMPTY LINE BELOW ###

"""
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="ascii", newline="\n") as config_file:
        config_file.write(config)
